-- ============================================================
-- 1. Base Entity: STUDENT
-- ============================================================
CREATE TABLE DASC5306_Fall25_S001_T8_Student (
    netID VARCHAR2(10) PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    email VARCHAR2(25) UNIQUE NOT NULL,
    password VARCHAR2(50) NOT NULL,
    phoneNo VARCHAR2(15),
    age INTEGER,
    date_of_enrollment DATE DEFAULT SYSDATE NOT NULL,
    cumulativeGPA NUMBER(4, 2),
    enrolled_dept VARCHAR2(50),
    nationality VARCHAR2(50),
    apt VARCHAR2(50),
    street VARCHAR2(100),
    zipcode VARCHAR2(10),
    county VARCHAR2(50)
);

-- ============================================================
-- 2. ARTIST and PATRON tables
-- ============================================================
CREATE TABLE DASC5306_Fall25_S001_T8_Artist (
    artist_ID VARCHAR2(30) PRIMARY KEY,
    no_of_followers NUMBER DEFAULT 0,
    FOREIGN KEY (artist_ID) REFERENCES DASC5306_Fall25_S001_T8_Student(netID) ON DELETE CASCADE
);

-- Create Patron table
CREATE TABLE DASC5306_Fall25_S001_T8_Patron (
    patronId VARCHAR2(20) PRIMARY KEY,
    FOREIGN KEY (patronId) REFERENCES DASC5306_Fall25_S001_T8_Student(netID) ON DELETE CASCADE
);

-- ============================================================
-- 3. PODCAST
-- ============================================================
CREATE TABLE DASC5306_Fall25_S001_T8_Podcast (
    podcast_ID VARCHAR2(20) PRIMARY KEY,
    name VARCHAR2(50),
    date_created DATE NOT NULL,
    description VARCHAR2(500),
    subscribers_count NUMBER DEFAULT 0
);

-- ============================================================
-- 4. EPISODE
-- ============================================================
CREATE TABLE DASC5306_Fall25_S001_T8_Episode (
    episodeNumber NUMBER GENERATED BY DEFAULT AS IDENTITY,
    podcast_ID VARCHAR2(20) NOT NULL,
    format VARCHAR2(10),
    title VARCHAR2(200) NOT NULL,
    sourceURL VARCHAR2(200),
    upload_date_time TIMESTAMP, 
    duration NUMBER CHECK (duration > 0),
    likes NUMBER DEFAULT 0,
    dislikes NUMBER DEFAULT 0,
    views NUMBER DEFAULT 0,
    PRIMARY KEY (podcast_ID, episodeNumber),
    FOREIGN KEY (podcast_ID) REFERENCES DASC5306_Fall25_S001_T8_Podcast(podcast_ID) ON DELETE CASCADE
);

-- ============================================================
-- 5. ADVERTISER and ADVERTISEMENT
-- ============================================================
CREATE TABLE DASC5306_Fall25_S001_T8_Advertiser (
    advertiserID VARCHAR2(20) PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    hqCity VARCHAR2(50),
    rate_per_view NUMBER(10, 2),
    employee_count NUMBER DEFAULT 0
);

-- Create Advertisement table
CREATE TABLE DASC5306_Fall25_S001_T8_Advertisement (
    adId VARCHAR2(20),
    advertiserID VARCHAR2(20),
    product_type VARCHAR2(50),
    duration NUMBER,
    hyperlink VARCHAR2(200),
    PRIMARY KEY (advertiserID, adId),
    FOREIGN KEY (advertiserID) REFERENCES DASC5306_Fall25_S001_T8_Advertiser(advertiserID)
);

-- ============================================================
-- 6. THEME
-- ============================================================
CREATE TABLE DASC5306_Fall25_S001_T8_Theme (
    podcast_ID VARCHAR2(20) NOT NULL,
    theme VARCHAR2(100) NOT NULL CHECK (theme IN ('educational', 'travel', 'interview', 'storytelling', 'health and fitness', 'news', 'technology')),
    PRIMARY KEY (podcast_ID, theme),
    FOREIGN KEY (podcast_ID) REFERENCES DASC5306_Fall25_S001_T8_Podcast(podcast_ID) ON DELETE CASCADE
);

-- ============================================================
-- 7. CATEGORY
-- ============================================================
CREATE TABLE DASC5306_Fall25_S001_T8_Category (
    advertiserID VARCHAR2(20),
    adId VARCHAR2(20),
    category VARCHAR2(100) UNIQUE NOT NULL,
    PRIMARY KEY (advertiserID, adId, category),
    FOREIGN KEY (advertiserID, adId) REFERENCES DASC5306_Fall25_S001_T8_Advertisement(advertiserID, adId) ON DELETE CASCADE
);

-- ============================================================
-- 8. SUBSCRIBES (Patron → Podcast)
-- ============================================================
CREATE TABLE DASC5306_Fall25_S001_T8_Subscribes (
    patronId VARCHAR2(20),
    podcast_ID VARCHAR2(20),
    PRIMARY KEY (patronId, podcast_ID),
    FOREIGN KEY (patronId) REFERENCES DASC5306_Fall25_S001_T8_Patron(patronId),
    FOREIGN KEY (podcast_ID) REFERENCES DASC5306_Fall25_S001_T8_Podcast(podcast_ID)
);

-- ============================================================
-- 9. LISTENS (Patron → Episode)
-- ============================================================
CREATE TABLE DASC5306_Fall25_S001_T8_Listens (
    patronId VARCHAR2(20),
    episodeNumber NUMBER,
    podcast_ID VARCHAR2(20),
    timeListened INTEGER,
    listenTimestamp TIMESTAMP,
    location VARCHAR2(20),
    duration NUMBER(20) CHECK (duration > 0),
    likes_dislikes INTEGER,
    PRIMARY KEY (patronId, podcast_ID, episodeNumber),
    FOREIGN KEY (patronId) REFERENCES DASC5306_Fall25_S001_T8_Patron(patronId),
    FOREIGN KEY (podcast_ID, episodeNumber) REFERENCES DASC5306_Fall25_S001_T8_Episode(podcast_ID, episodeNumber)
);

-- ============================================================
-- 10. UPLOADS / CREATES RELATIONSHIPS
-- ============================================================
CREATE TABLE DASC5306_Fall25_S001_T8_Uploads_Creates_ArtPod (
    artist_ID VARCHAR2(30),
    podcast_ID VARCHAR2(20),
    PRIMARY KEY (artist_ID, podcast_ID),
    FOREIGN KEY (artist_ID) REFERENCES DASC5306_Fall25_S001_T8_Artist(artist_ID),
    FOREIGN KEY (podcast_ID) REFERENCES DASC5306_Fall25_S001_T8_Podcast(podcast_ID)
);

CREATE TABLE DASC5306_Fall25_S001_T8_Creates_Uploaded_ArtEpi (
    artist_ID VARCHAR2(30),
    episodeNumber NUMBER,
    podcast_ID VARCHAR2(20),
    PRIMARY KEY (artist_ID, episodeNumber, podcast_ID),
    FOREIGN KEY (artist_ID) REFERENCES DASC5306_Fall25_S001_T8_Artist(artist_ID),
    FOREIGN KEY (episodeNumber, podcast_ID) REFERENCES DASC5306_Fall25_S001_T8_Episode(episodeNumber, podcast_ID)
);

-- ============================================================
-- 11. DISPLAYEDIN (Advertisement placement in Episodes)
-- ============================================================
CREATE TABLE DASC5306_Fall25_S001_T8_DisplayedIn (
    episodeNumber NUMBER,
    podcast_ID VARCHAR2(20),
    advertiserID VARCHAR2(20),
    adId VARCHAR2(20),
    timestamp TIMESTAMP,
    cost NUMBER(10, 2),
    PRIMARY KEY (episodeNumber, podcast_ID, advertiserID, adId),
    FOREIGN KEY (episodeNumber, podcast_ID) REFERENCES DASC5306_Fall25_S001_T8_Episode(episodeNumber, podcast_ID),
    FOREIGN KEY (advertiserID, adId) REFERENCES DASC5306_Fall25_S001_T8_Advertisement(advertiserID, adId)
);

-- ============================================================
-- TRIGGER : Podcast.Subscribers_count
-- ============================================================
CREATE OR REPLACE TRIGGER trg_update_subscribers_count
AFTER INSERT OR DELETE ON DASC5306_Fall25_S001_T8_Subscribes
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        UPDATE DASC5306_Fall25_S001_T8_Podcast
        SET subscribers_count = NVL(subscribers_count, 0) + 1
        WHERE podcast_ID = :NEW.podcast_ID;
    ELSIF DELETING THEN
        UPDATE DASC5306_Fall25_S001_T8_Podcast
        SET subscribers_count = NVL(subscribers_count, 0) - 1
        WHERE podcast_ID = :OLD.podcast_ID;
    END IF;
END;
/

-- ============================================================
-- TRIGGER : Episode.likes, Episode.dislikes, Episode.views
-- ============================================================
CREATE OR REPLACE TRIGGER trg_update_episode_engagement
AFTER INSERT OR DELETE OR UPDATE ON DASC5306_Fall25_S001_T8_Listens
FOR EACH ROW
BEGIN
    -- If a new listen is added → increment views
    IF INSERTING THEN
        UPDATE DASC5306_Fall25_S001_T8_Episode
        SET views = NVL(views, 0) + 1
        WHERE podcast_ID = :NEW.podcast_ID AND episodeNumber = :NEW.episodeNumber;

        IF :NEW.likes_dislikes = 1 THEN
            UPDATE DASC5306_Fall25_S001_T8_Episode
            SET likes = NVL(likes, 0) + 1
            WHERE podcast_ID = :NEW.podcast_ID AND episodeNumber = :NEW.episodeNumber;
        ELSIF :NEW.likes_dislikes = -1 THEN
            UPDATE DASC5306_Fall25_S001_T8_Episode
            SET dislikes = NVL(dislikes, 0) + 1
            WHERE podcast_ID = :NEW.podcast_ID AND episodeNumber = :NEW.episodeNumber;
        END IF;
    END IF;

    -- If listen is deleted → decrement counts
    IF DELETING THEN
        UPDATE DASC5306_Fall25_S001_T8_Episode
        SET views = NVL(views, 0) - 1
        WHERE podcast_ID = :OLD.podcast_ID AND episodeNumber = :OLD.episodeNumber;
        IF :OLD.likes_dislikes = 1 THEN
            UPDATE DASC5306_Fall25_S001_T8_Episode
            SET likes = NVL(likes, 0) - 1
            WHERE podcast_ID = :OLD.podcast_ID AND episodeNumber = :OLD.episodeNumber;
        ELSIF :OLD.likes_dislikes = -1 THEN
            UPDATE DASC5306_Fall25_S001_T8_Episode
            SET dislikes = NVL(dislikes, 0) - 1
            WHERE podcast_ID = :OLD.podcast_ID AND episodeNumber = :OLD.episodeNumber;
        END IF;
    END IF;
END;
/

-- ============================================================
-- TRIGGER : Advertiser.employee_count
-- ============================================================
CREATE OR REPLACE TRIGGER trg_update_employee_count
AFTER INSERT OR DELETE ON DASC5306_Fall25_S001_T8_Advertisement
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        UPDATE DASC5306_Fall25_S001_T8_Advertiser
        SET employee_count = NVL(employee_count, 0) + 1
        WHERE advertiserID = :NEW.advertiserID;
    ELSIF DELETING THEN
        UPDATE DASC5306_Fall25_S001_T8_Advertiser
        SET employee_count = NVL(employee_count, 0) - 1
        WHERE advertiserID = :OLD.advertiserID;
    END IF;
END;
/
